"""Project constants."""

TRADING_DAYS_PER_YEAR: int = 252
RANDOM_SEED: int = 42
DEFAULT_TICKER: str = "SPY"
DEFAULT_N_MC_PATHS: int = 500_000
DEFAULT_BINOMIAL_STEPS: int = 1000

MONEYNESS_LOWER: float = 0.80
MONEYNESS_UPPER: float = 1.20
MIN_OPTION_PRICE: float = 0.10
MIN_DAYS_TO_EXPIRY: int = 7
MAX_BID_ASK_SPREAD_PCT: float = 0.20
MIN_VOLUME_PLUS_OI: int = 10

IV_LOWER_BOUND: float = 0.01
IV_UPPER_BOUND: float = 3.00

FALLBACK_RISK_FREE_RATE: float = 0.043
FALLBACK_DIVIDEND_YIELD: float = 0.013

PLOT_DPI: int = 150
PLOT_STYLE: str = 'seaborn-v0_8-whitegrid'
FIG_SIZE_DEFAULT: tuple = (10, 6)
FIG_SIZE_WIDE: tuple = (14, 8)
FIG_SIZE_GRID: tuple = (16, 10)
